#!/usr/bin/env python3
"""Generate the specialized sieve shaders from the checked-in CPU prime table."""

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
PRIME_TABLE = ROOT / "include/ap27_v3d/small_primes.hpp"
MOD = 258559632607830
FIRST_STAGE_PRIMES = 32
MIDDLE_STAGE_PRIMES = 56
FIRST_INLINE_PRIMES = 6
INLINE_PRIMES = (
    (61, 60, 0), (67, 25, 61), (71, 20, 128),
    (73, 8, 199), (79, 52, 272), (83, 40, 351),
)


def read_primes():
    source = PRIME_TABLE.read_text()
    primes = [tuple(map(int, match)) for match in re.findall(
        r"^\s*\{(\d+)u, (\d+)u, (\d+)u\},$", source, re.MULTILINE
    )]
    if len(primes) != 83 or tuple(primes[:FIRST_INLINE_PRIMES]) != INLINE_PRIMES or primes[-1][0] != 541:
        raise ValueError("unexpected AP27 prime table")
    offset = 0
    for prime, coefficient, row_offset in primes:
        if row_offset != offset or pow(2, 30, prime) != coefficient:
            raise ValueError(f"invalid prime-table entry for {prime}")
        offset += prime
    if offset != 23693:
        raise ValueError("unexpected mask-table size")
    return primes


def first_stage_fragment(primes):
    lines = [
        "// Generated by tools/gen_sieve.py; primes 1-6 are in tile.comp.",
        f"// Apply primes 7-{FIRST_STAGE_PRIMES} to both shifts before storing early records.",
        "uvec4 apply_early_prime_masks(uint a,uint b,uvec4 m) {",
    ]
    for i in range(FIRST_INLINE_PRIMES, FIRST_STAGE_PRIMES):
        prime, coefficient, offset = primes[i]
        lines.extend([
            f"    uint index{i}=(a+{coefficient}u*b)%{prime}u+{offset}u;",
            f"    m &= pair_data.m[index{i}];",
        ])
        if (i + 1) % 5 == 0:
            lines.append("    if((m.x|m.y|m.z|m.w)==0u) return m;")
    return "\n".join([*lines, "    return m;", "}", ""])


def final_stage_fragment(primes, start=None, function_name="apply_late_prime_masks"):
    start = FIRST_STAGE_PRIMES if start is None else start
    lines = [
        f"// Generated by tools/gen_sieve.py; apply primes {start+1}-{len(primes)} to one tagged shift.",
        f"uvec2 {function_name}(uint a,uint b,uvec2 m,bool second_shift) {{",
    ]
    for i in range(start, len(primes)):
        prime, coefficient, offset = primes[i]
        end = offset + prime
        rotation = (64 * MOD) % prime
        lines.extend([
            f"    uint index{i}=(a+{coefficient}u*b)%{prime}u+{offset}u;",
            f"    index{i}+=second_shift ? {rotation}u : 0u;",
            f"    if(index{i}>={end}u)index{i}-={prime}u;",
            f"    m &= mask_data.m[index{i}];",
        ])
        if (i + 1) % 5 == 0 and i + 1 < len(primes):
            lines.append("    if((m.x|m.y)==0u) return m;")
    return "\n".join([*lines, "    return m;", "}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify generated shaders match the checked-in files")
    args = parser.parse_args()
    layout = (ROOT / "include/ap27_v3d/tile_layout.hpp").read_text()
    count = re.search(r"FIRST_STAGE_PRIME_COUNT\s*=\s*(\d+)", layout)
    if count is None or int(count[1]) != FIRST_STAGE_PRIMES:
        raise ValueError("host paired-mask extent does not match the first sieve stage")
    primes = read_primes()
    outputs = {
        ROOT / "shaders/sieve_masks_early.glsl": first_stage_fragment(primes),
        ROOT / "shaders/sieve_masks_middle.glsl": final_stage_fragment(
            primes[:MIDDLE_STAGE_PRIMES], function_name="apply_middle_prime_masks"),
        ROOT / "shaders/sieve_masks_late.glsl": final_stage_fragment(primes, start=MIDDLE_STAGE_PRIMES),
    }
    for path, source in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != source:
                raise SystemExit(f"outdated generated shader: {path}")
        else:
            path.write_text(source)
    print(f"{'checked' if args.check else 'generated'} {len(primes)} sieve primes")


if __name__ == "__main__":
    main()
